name: null
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- vcflib=1.0.0_rc2
- _libgcc_mutex=0.1
- bzip2=1.0.8
- ca-certificates=2020.10.14
#- certifi=2020.6.203
- libedit=3.1.20191231
- libffi=3.3
#- libgcc-ng=9.1.0
#- libstdcxx-ng=9.1.0
- ncurses=6.2
- pip=19.3.1
- python=2.7.18
- readline=8.0
- setuptools=44.0.0
- sqlite=3.33.0
- tk=8.6.10
- wheel=0.35.1
- xz=5.2.5
- zlib=1.2.11

